.TH FAKE-HWCLOCK 8 "20 April 2013" "Version 0.1"
.SH NAME
fake-hwclock \- Set/Save fake hardware clock
.SH SYNOPSIS
.B fake-hwclock
.SH DESCRIPTION
.SH EXIT STATUS
fake-hwclock returns a zero exit status if it successfully saves or sets the system time. Non zero is returned in the case of failure (for example when not run by root).
.SH AUTHOR
Xan Manning (hello (at) xan-manning.co.uk)
